### ISSUE TITLE
leetcode打卡——js 画画

### ISSUE THREAD

**Issue by guojun6** [Imatvoid/leetcode-week-attendance#1]
`-------------------题目-------------------------`
`序号 题目 简短总结`
415 Add Strings  字符串相加，得注意大数字取余和除法运算得精度
445 Add Two Numbers II  跟No.2相似，但是换了链表结构
`------------------题解地址-----------------------`
`issue的link`
[ Add Strings ](https://juejin.im/post/5d40dfb15188255d9140719c)
[ Add Two Numbers II ](https://juejin.im/post/5d403f1c6fb9a06b017e2a98)

`-------------------补充:------------------------`
其他题目之前做了，就不写题解了
`------------------------------------------------`

**Comment by Imatvoid** [comment]
终于发现一个做了推荐题目的哈哈,发现模板的感觉了吗
