### ISSUE TITLE
LeetCode第三周-python-alaric

### ISSUE THREAD

**Issue by Alarical** [Imatvoid/leetcode-week-attendance#10]
-------------------题目-------------------------
序号 题目 简短总结
76  Minimum Path Sum    
392 House Robber   
110 Minimum Path Sum    
664 Counting Bits   
516 Paint House II  
534 House Robber II 
149 Best Time to Buy and Sell Stock
150 Best Time to Buy and Sell Stock II   
151 Best Time to Buy and Sell Stock III  
393 Best Time to Buy and Sell Stock IV   
602 Russian Doll Envelopes
------------------题解地址-----------------------
Git地址：https://github.com/Alarical/Interview/tree/master/LintCode
------------------补充-----------------------
原来是一周一打卡啊，记成两周了。LintCode题目难度比leetCode稍简单，所以题以M难度为主，少数Easy和Hard

**Comment by Imatvoid** [comment]
做的挺多的,已记录
