### ISSUE TITLE
 leetcode打卡-Java自闭工程师

### ISSUE THREAD

**Issue by doublepay** [Imatvoid/leetcode-week-attendance#2]
`-------------------题目-------------------------`
`序号 题目 简短总结`
16 最接近的三数之和     与三数之和一个类型
46  全排列                       递归与回溯法
58 最后一个单词的长度  字符串的截取
7   整数反转                     一次构建反转整数的一位数字，预先检查向原整数附加另一位数字是否 
                                        会导致溢出
415 字符串相加              竖式相加，由低位到高位
`------------------题解地址-----------------------`
`issue的link`
无
`------------------周赛截图:----------------------`
![image](https://user-images.githubusercontent.com/37472886/62299904-71e74c80-b4a8-11e9-8209-ade6b05cf834.png)

`-------------------补充:------------------------`

`------------------------------------------------`

**Comment by Imatvoid** [comment]
可以把全排列 和组合弄一个专题.对比
