### ISSUE TITLE
leetcode打卡 - js-NAI

### ISSUE THREAD

**Issue by NanaYang007** [Imatvoid/leetcode-week-attendance#3]
-------------------题目-------------------------
章节 - 数组
1、从排序数组中删除重复项
6、两个数组的交集 II
8、移动零
题目地址：https://leetcode-cn.com/explore/featured/card/top-interview-questions-easy/1/array/21/

------------------题解地址-----------------------
博客记录（随时更新）：https://blog.csdn.net/Nana_9457/article/details/98185452
“数字数组”中的1，2；
“链表”中的1；

**Comment by Imatvoid** [comment]
继续坚持~~
