### ISSUE TITLE
LeetCode打卡-java-lj

### ISSUE THREAD

**Issue by explorerman** [Imatvoid/leetcode-week-attendance#4]
`-------------------题目-------------------------`
`序号 题目 简短总结`
198 house robber  动态规划简单题，也可以使用奇偶位置记录当前最大值
20 valid parentheses  栈的简单使用，遍历字符串，将左半部分压入栈，并比较栈顶与栈内元素是否一对，符合要求，出栈。
695 max area of island DFS和BFS的应用
200 number of islands DFS和BFS的应用
11 Container With Most Water  暴力破解解决
`------------------题解地址-----------------------`
`issue的link`
在自己的百度云账号
`------------------周赛截图:----------------------`
无
`-------------------补充:------------------------`
无
`------------------------------------------------`

**Comment by Imatvoid** [comment]
~继续坚持
