### ISSUE TITLE
LeetCode打卡-python-alaric

### ISSUE THREAD

**Issue by Alarical** [Imatvoid/leetcode-week-attendance#5]
`-------------------题目-------------------------`
#序号 题目 简短总结
114、Unique Paths    DP相关（下面都是）
115、Unique Paths II
116、Jump Game 
191、Maximum Product Subarray
512、Paint House 
515、Decode Ways
699、Coin Change
`------------------题解地址-----------------------`
Git地址：https://github.com/Alarical/Interview/tree/master/LintCode
点python或java文字可以跳转到代码文件。（如果有java版本的话）
相关代码均通过lintcode的在线测试。

**Comment by Imatvoid** [comment]
做的很多~ JumpGame2 可以做一下
