### ISSUE TITLE
leetcode打卡-猪头少年

### ISSUE THREAD

**Issue by kyjo2014** [Imatvoid/leetcode-week-attendance#6]
`-------------------题目-------------------------`
`序号 题目 简短总结`
62 uniquePath 标准动态规划，递推式当前格子次数等于左上之和
70 climb stairs  标准动态规划，k[i] = k[i-1] + k[i-2]
`-------------------补充:------------------------`
题解下周再传，还在笔记本上
`------------------------------------------------`

**Comment by Imatvoid** [comment]
动态规划确实值得好好思考
