### ISSUE TITLE
leetcode打卡-PHP-逸晖

### ISSUE THREAD

**Issue by hzqyihui** [Imatvoid/leetcode-week-attendance#7]
`-------------------题目-------------------------`
`序号 题目 简短总结`
3  无重复字符的最长子串  利用滑动窗口实现
8  字符串转换整数 (atoi)   循环比较，若头部为0，后面需要筛掉
9  回文数  字符串二分后，头尾挨个比较，遇到不同则不是回文数
58  最后一个单词的长度  以空格分割为数组后，去掉空值数组，取数组最后一个值的长度
100  相同的树  利用递归，判断两个数的左右子树对应相同才返回true
415  字符串相加  需保持两数位数相同（低位数头部以0填充），从最低位开始相加，有进位，需在次低位加上
1137  第 N 个泰波那契数  利用递归实现，但时间会超限，最后看到此数列有其他的规则，利用递归还是实现了。
`------------------题解地址-----------------------`
`issue的link`
`------------------周赛截图:----------------------`

`-------------------补充:------------------------`

`------------------------------------------------`

**Comment by Imatvoid** [comment]
做的好多~
