### ISSUE TITLE
leetcode打卡第二周 - js-NAI

### ISSUE THREAD

**Issue by NanaYang007** [Imatvoid/leetcode-week-attendance#8]
字符串刷题：
1、原地反转字符串数组（判错3-4次）
审题：原地、利用o(1)空间
注意点：注意中间停止位置，需要判断奇偶性吗？
思路：一个for循环，Math.floor(len/2)前后交换（绕过奇偶）
结果：执行时间较快 超过99%
其他题解：
1）🆕利用数组交换两个数
2）直接s.reverse()，也是原地反转

2、返回字符串中唯一的字符，没有返回-1（判错3-4次）
审题：题目中对于完备性有明确指示返回-1，所以这里要考虑全面，输入为[]，输入为‘cc’等等情况（此处两次判错）
思路：利用前后的indexOf（第一次出现）的加和与字符串lengh的关系
注意点：一开始想当然前后indexOf相等，脑中要有图，仔细的画出“过程”

3、有效的字母异位词（判错2次 - 马虎）
思路：利用indexOf和splice结合
结果：执行时间慢，1408ms。。。
其他题解：
⚠️利用正则：注意新建正则写法new RegExp(s[0],'g')；注意这一句s.length!=t.length，不添加则因为‘g’出错，但’g’可以加快判断速度。

记录在博客中 字符串1-3题
https://blog.csdn.net/Nana_9457/article/details/98185452

**Comment by Imatvoid** [comment]
已记录~
